services:
  - name: rq-worker
    type: worker
    command: "rq worker --url $REDIS_URL amazon-returns-task-queue"
    envVars:
      - key: REDIS_URL
        fromDatabase:
          name: my-redis-database
          property: host
