services:
  - type: worker
    name: queue
    region: ohio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "rq worker --url $REDIS_URL amazon-returns-task-queue"
    autoDeploy: false
